modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://hammy275.com/immersivemcissues"
license = "GNU LGPLv3"
logoFile= "immersivemc_logo.png"

[[mods]]
modId = "immersivemc"
version = "${version}"
displayName = "ImmersiveMC"
displayURL = "https://hammy275.com/immersivemcwiki"
authors = "hammy275"
updateJSONURL = "https://api.modrinth.com/updates/immersivemc/forge_updates.json"
description = '''
Minimizes the need to interact with GUIs in Minecraft!

Works great both in and out of VR!

Requires the MC VR API mod if you want to use this the best in VR!

Thanks to NahNotFox for the bundle bag model (the default)!

Thanks to yaosiqian for Simplified Chinese translations!

Thanks to Yermak for the Russian translations!

Thanks to the Vivecraft developers for inspiration for the backpack, and to various members of the Discord for ideas!

Thanks to the guide from leo3418 for the Config Screen!
'''
#logoFile = ""

[[dependencies.immersivemc]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersivemc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersivemc]]
modId = "architectury"
mandatory = true
versionRange = "[7.0.66,)"
ordering = "AFTER"
side = "BOTH"