modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "immersivemc"
version = "1.1.0"
displayName = "ImmersiveMC"
authors = "hammy3502"
description = '''
Minimizes the need to interact with GUIs in Minecraft!

Works great both in and out of VR!

Requires the MC VR API mod if you want to use this the best in VR!

Thanks to yaosiqian for Simplified Chinese translations!

Thanks to the Vivecraft developers for inspiration for the backpack, and to various members of the Discord for ideas!

Thanks to the guide from leo3418 for the Config Screen!
'''
#logoFile = ""

[[dependencies.immersivemc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersivemc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersivemc]]
modId = "architectury"
mandatory = true
versionRange = "[4.9.83,)"
ordering = "AFTER"
side = "BOTH"